# Generated by Django 3.1.4 on 2020-12-29 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0002_auto_20201221_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decision',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
