# Generated by Django 3.1.4 on 2020-12-31 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_through_relations(apps, schema_editor):
    Team = apps.get_model('votes', 'Team')
    Membership = apps.get_model('votes', 'Membership')

    for team in Team.objects.all():
        for member in team.members.all():
            membership = Membership(team=team, user=member, invitation=None)
            membership.save()


class Migration(migrations.Migration):

    # replaces = [('votes', '0006_auto_20201231_1242'), ('votes', '0007_auto_20201231_1242'), ('votes', '0008_remove_team_members'), ('votes', '0009_team_members')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0005_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votes.invitation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_member'),
        ),
        migrations.RunPython(
            code=create_through_relations,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='votes.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
