# Generated by Django 3.1 on 2020-09-04 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Die Mobilnummer ist nur im Format '0123/456789' erlaubt.", regex='01\\d{2}\\/\\d{6,7}')])),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Die Anschrift muss im Format 'Straße Nr., PLZ Stadt' angegeben werden.", regex='.*\\,\\s\\d{5}\\s\\w{3,}')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.mentor')),
            ],
        ),
    ]
