# Generated by Django 3.1.1 on 2020-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_auto_20201013_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='nick',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
