# Generated by Django 3.1.12 on 2021-07-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_auto_20201015_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='nick',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='supervision',
        ),
        migrations.RemoveField(
            model_name='program',
            name='slug',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentoring.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='faculty',
            field=models.CharField(choices=[('MB', 'Maschinenbau'), ('EIT', 'Elektro- & Informationstechnik'), ('VST', 'Verfahrens- & Systemtechnik'), ('MA', 'Mathematik')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
    ]
