# Generated by Django 3.1.12 on 2021-08-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_auto_20210720_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
    ]
